import { ICountries } from "../interfaces/CountryInterface";

const countries: ICountries[] = [
  { id: 1, name: 'Afghanistan', code: 'AF' },
  { id: 2, name: 'Albania', code: 'AL' },
  { id: 3, name: 'Algeria', code: 'DZ' },
  { id: 4, name: 'Andorra', code: 'AD' },
  { id: 5, name: 'Angola', code: 'AO' },
  { id: 6, name: 'Antigua and Barbuda', code: 'AG' },
  { id: 7, name: 'Argentina', code: 'AR' },
  { id: 8, name: 'Armenia', code: 'AM' },
  { id: 9, name: 'Australia', code: 'AU' },
  { id: 10, name: 'Austria', code: 'AT' },
  { id: 11, name: 'Azerbaijan', code: 'AZ' },
  { id: 12, name: 'Bahamas', code: 'BS' },
  { id: 13, name: 'Bahrain', code: 'BH' },
  { id: 14, name: 'Bangladesh', code: 'BD' },
  { id: 15, name: 'Barbados', code: 'BB' },
  { id: 16, name: 'Belarus', code: 'BY' },
  { id: 17, name: 'Belgium', code: 'BE' },
  { id: 18, name: 'Belize', code: 'BZ' },
  { id: 19, name: 'Benin', code: 'BJ' },
  { id: 20, name: 'Bhutan', code: 'BT' },
  { id: 21, name: 'Bolivia', code: 'BO' },
  { id: 22, name: 'Bosnia and Herzegovina', code: 'BA' },
  { id: 23, name: 'Botswana', code: 'BW' },
  { id: 24, name: 'Brazil', code: 'BR' },
  { id: 25, name: 'Brunei', code: 'BN' },
  { id: 26, name: 'Bulgaria', code: 'BG' },
  { id: 27, name: 'Burkina Faso', code: 'BF' },
  { id: 28, name: 'Burundi', code: 'BI' },
  { id: 29, name: 'Cabo Verde', code: 'CV' },
  { id: 30, name: 'Cambodia', code: 'KH' },
  { id: 31, name: 'Cameroon', code: 'CM' },
  { id: 32, name: 'Canada', code: 'CA' },
  { id: 33, name: 'Central African Republic', code: 'CF' },
  { id: 34, name: 'Chad', code: 'TD' },
  { id: 35, name: 'Chile', code: 'CL' },
  { id: 36, name: 'China', code: 'CN' },
  { id: 37, name: 'Colombia', code: 'CO' },
  { id: 38, name: 'Comoros', code: 'KM' },
  { id: 39, name: 'Congo (Congo-Brazzaville)', code: 'CG' },
  { id: 40, name: 'Costa Rica', code: 'CR' },
  { id: 41, name: 'Croatia', code: 'HR' },
  { id: 42, name: 'Cuba', code: 'CU' },
  { id: 43, name: 'Cyprus', code: 'CY' },
  { id: 44, name: 'Czechia (Czech Republic)', code: 'CZ' },
  { id: 45, name: 'Denmark', code: 'DK' },
  { id: 46, name: 'Djibouti', code: 'DJ' },
  { id: 47, name: 'Dominica', code: 'DM' },
  { id: 48, name: 'Dominican Republic', code: 'DO' },
  { id: 49, name: 'Ecuador', code: 'EC' },
  { id: 50, name: 'Egypt', code: 'EG' },
  { id: 51, name: 'El Salvador', code: 'SV' },
  { id: 52, name: 'Equatorial Guinea', code: 'GQ' },
  { id: 53, name: 'Eritrea', code: 'ER' },
  { id: 54, name: 'Estonia', code: 'EE' },
  { id: 55, name: 'Eswatini', code: 'SZ' },
  { id: 56, name: 'Ethiopia', code: 'ET' },
  { id: 57, name: 'Fiji', code: 'FJ' },
  { id: 58, name: 'Finland', code: 'FI' },
  { id: 59, name: 'France', code: 'FR' },
  { id: 60, name: 'Gabon', code: 'GA' },
  { id: 61, name: 'Gambia', code: 'GM' },
  { id: 62, name: 'Georgia', code: 'GE' },
  { id: 63, name: 'Germany', code: 'DE' },
  { id: 64, name: 'Ghana', code: 'GH' },
  { id: 65, name: 'Greece', code: 'GR' },
  { id: 66, name: 'Grenada', code: 'GD' },
  { id: 67, name: 'Guatemala', code: 'GT' },
  { id: 68, name: 'Guinea', code: 'GN' },
  { id: 69, name: 'Guinea-Bissau', code: 'GW' },
  { id: 70, name: 'Guyana', code: 'GY' },
  { id: 71, name: 'Haiti', code: 'HT' },
  { id: 72, name: 'Holy See', code: 'VA' },
  { id: 73, name: 'Honduras', code: 'HN' },
  { id: 74, name: 'Hungary', code: 'HU' },
  { id: 75, name: 'Iceland', code: 'IS' },
  { id: 76, name: 'India', code: 'IN' },
  { id: 77, name: 'Indonesia', code: 'ID' },
  { id: 78, name: 'Iran', code: 'IR' },
  { id: 79, name: 'Iraq', code: 'IQ' },
  { id: 80, name: 'Ireland', code: 'IE' },
  { id: 81, name: 'Israel', code: 'IL' },
  { id: 82, name: 'Italy', code: 'IT' },
  { id: 83, name: 'Jamaica', code: 'JM' },
  { id: 84, name: 'Japan', code: 'JP' },
  { id: 85, name: 'Jordan', code: 'JO' },
  { id: 86, name: 'Kazakhstan', code: 'KZ' },
  { id: 87, name: 'Kenya', code: 'KE' },
  { id: 88, name: 'Kiribati', code: 'KI' },
  { id: 89, name: 'Korea, Democratic People\'s Republic of (North Korea)', code: 'KP' },
  { id: 90, name: 'Korea, Republic of (South Korea)', code: 'KR' },
  { id: 91, name: 'Kuwait', code: 'KW' },
  { id: 92, name: 'Kyrgyzstan', code: 'KG' },
  { id: 93, name: 'Laos', code: 'LA' },
  { id: 94, name: 'Latvia', code: 'LV' },
  { id: 95, name: 'Lebanon', code: 'LB' },
  { id: 96, name: 'Lesotho', code: 'LS' },
  { id: 97, name: 'Liberia', code: 'LR' },
  { id: 98, name: 'Libya', code: 'LY' },
  { id: 99, name: 'Liechtenstein', code: 'LI' },
  { id: 100, name: 'Lithuania', code: 'LT' },
  { id: 101, name: 'Luxembourg', code: 'LU' },
  { id: 102, name: 'Madagascar', code: 'MG' },
  { id: 103, name: 'Malawi', code: 'MW' },
  { id: 104, name: 'Malaysia', code: 'MY' },
  { id: 105, name: 'Maldives', code: 'MV' },
  { id: 106, name: 'Mali', code: 'ML' },
  { id: 107, name: 'Malta', code: 'MT' },
  { id: 108, name: 'Marshall Islands', code: 'MH' },
  { id: 109, name: 'Mauritania', code: 'MR' },
  { id: 110, name: 'Mauritius', code: 'MU' },
  { id: 111, name: 'Mexico', code: 'MX' },
  { id: 112, name: 'Micronesia, Federated States of', code: 'FM' },
  { id: 113, name: 'Moldova', code: 'MD' },
  { id: 114, name: 'Monaco', code: 'MC' },
  { id: 115, name: 'Mongolia', code: 'MN' },
  { id: 116, name: 'Montenegro', code: 'ME' },
  { id: 117, name: 'Morocco', code: 'MA' },
  { id: 118, name: 'Mozambique', code: 'MZ' },
  { id: 119, name: 'Myanmar', code: 'MM' },
  { id: 120, name: 'Namibia', code: 'NA' },
  { id: 121, name: 'Nauru', code: 'NR' },
  { id: 122, name: 'Nepal', code: 'NP' },
  { id: 123, name: 'Netherlands', code: 'NL' },
  { id: 124, name: 'New Zealand', code: 'NZ' },
  { id: 125, name: 'Nicaragua', code: 'NI' },
  { id: 126, name: 'Niger', code: 'NE' },
  { id: 127, name: 'Nigeria', code: 'NG' },
  { id: 128, name: 'North Macedonia', code: 'MK' },
  { id: 129, name: 'Norway', code: 'NO' },
  { id: 130, name: 'Oman', code: 'OM' },
  { id: 131, name: 'Pakistan', code: 'PK' },
  { id: 132, name: 'Palau', code: 'PW' },
  { id: 133, name: 'Panama', code: 'PA' },
  { id: 134, name: 'Papua New Guinea', code: 'PG' },
  { id: 135, name: 'Paraguay', code: 'PY' },
  { id: 136, name: 'Peru', code: 'PE' },
  { id: 137, name: 'Philippines', code: 'PH' },
  { id: 138, name: 'Poland', code: 'PL' },
  { id: 139, name: 'Portugal', code: 'PT' },
  { id: 140, name: 'Qatar', code: 'QA' },
  { id: 141, name: 'Romania', code: 'RO' },
  { id: 142, name: 'Russia', code: 'RU' },
  { id: 143, name: 'Rwanda', code: 'RW' },
  { id: 144, name: 'Saint Kitts and Nevis', code: 'KN' },
  { id: 145, name: 'Saint Lucia', code: 'LC' },
  { id: 146, name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { id: 147, name: 'Samoa', code: 'WS' },
  { id: 148, name: 'San Marino', code: 'SM' },
  { id: 149, name: 'Sao Tome and Principe', code: 'ST' },
  { id: 150, name: 'Saudi Arabia', code: 'SA' },
  { id: 151, name: 'Senegal', code: 'SN' },
  { id: 152, name: 'Serbia', code: 'RS' },
  { id: 153, name: 'Seychelles', code: 'SC' },
  { id: 154, name: 'Sierra Leone', code: 'SL' },
  { id: 155, name: 'Singapore', code: 'SG' },
  { id: 156, name: 'Slovakia', code: 'SK' },
  { id: 157, name: 'Slovenia', code: 'SI' },
  { id: 158, name: 'Solomon Islands', code: 'SB' },
  { id: 159, name: 'Somalia', code: 'SO' },
  { id: 160, name: 'South Africa', code: 'ZA' },
  { id: 161, name: 'South Sudan', code: 'SS' },
  { id: 162, name: 'Spain', code: 'ES' },
  { id: 163, name: 'Sri Lanka', code: 'LK' },
  { id: 164, name: 'Sudan', code: 'SD' },
  { id: 165, name: 'Suriname', code: 'SR' },
  { id: 166, name: 'Sweden', code: 'SE' },
  { id: 167, name: 'Switzerland', code: 'CH' },
  { id: 168, name: 'Syria', code: 'SY' },
  { id: 169, name: 'Tajikistan', code: 'TJ' },
  { id: 170, name: 'Tanzania', code: 'TZ' },
  { id: 171, name: 'Thailand', code: 'TH' },
  { id: 172, name: 'Timor-Leste', code: 'TL' },
  { id: 173, name: 'Togo', code: 'TG' },
  { id: 174, name: 'Tonga', code: 'TO' },
  { id: 175, name: 'Trinidad and Tobago', code: 'TT' },
  { id: 176, name: 'Tunisia', code: 'TN' },
  { id: 177, name: 'Turkey', code: 'TR' },
  { id: 178, name: 'Turkmenistan', code: 'TM' },
  { id: 179, name: 'Tuvalu', code: 'TV' },
  { id: 180, name: 'Uganda', code: 'UG' },
  { id: 181, name: 'Ukraine', code: 'UA' },
  { id: 182, name: 'United Arab Emirates', code: 'AE' },
  { id: 183, name: 'United Kingdom', code: 'GB' },
  { id: 184, name: 'United States of America', code: 'US' },
  { id: 185, name: 'Uruguay', code: 'UY' },
  { id: 186, name: 'Uzbekistan', code: 'UZ' },
  { id: 187, name: 'Vanuatu', code: 'VU' },
  { id: 188, name: 'Venezuela', code: 'VE' },
  { id: 189, name: 'Vietnam', code: 'VN' },
  { id: 190, name: 'Yemen', code: 'YE' },
  { id: 191, name: 'Zambia', code: 'ZM' },
  { id: 192, name: 'Zimbabwe', code: 'ZW' },
];

export function getCountries(): ICountries[] {
  return countries;
}
